function randomCitat() {
       const citat = [
        '"The only limit to our realization of tomorrow is our doubts of today." - Franklin D. Roosevelt',
        '"Stay hungry, stay foolish." - Steve Jobs',
        '"I have a dream." - Martin Luther King Jr.',
        '"In the middle of difficulty lies opportunity." - Albert Einstein',
        '"It always seems impossible until it`s done." - Nelson Mandela',
        '"Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill',
        '"Hakuna Matata!" - Lejonkungen',
        '"May the Force be with you." - Star Wars',
        '"I`m gonna make him an offer he can`t refuse." - Gudfadern',
        '"Be the change that you wish to see in the world." - Mahatma Gandhi',
        '"The only thing we have to fear is fear itself." - Franklin D. Roosevelt',
        '"Just do it." - Nike',
        '"To be or not to be, that is the question." - William Shakespeare',
        '"Carpe Diem. Seize the day, boys." - Döda poeters sällskap',
        '"You miss 100% of the shots you don`t take." - Wayne Gretzky',
        '"Float like a butterfly, sting like a bee." - Muhammad Ali',
        '"Do or do not. There is no try." - Yoda (Star Wars)',
        '"All we have to decide is what to do with the time that is given us." - Gandalf (Sagan om Ringen)',
        '"Life is what happens when you`re busy making other plans." - John Lennon',
        '"Don`t cry because it`s over, smile because it happened." - Dr. Seus"',
        '"Simplicity is the ultimate sophistication." - Leonardo da Vinci',
        '"Do what you can, with what you have, where you are." - Theodore Roosevelt',
        '"Not all those who wander are lost." - J.R.R. Tolkien',
        '"Act as if what you do makes a difference. It does." - William James',
        '"Dream big and dare to fail." - Norman Vaughan',
        '"It does not matter how slowly you go as long as you do not stop." - Confucius',
        '"Life is really simple, but we insist on making it complicated." - Confucius',
        '"Believe you can and you`re halfway there." - Theodore Roosevelt',
        '"Keep your face always toward the sunshine—and shadows will fall behind you." - Walt Whitman',
        '"Everything you can imagine is real." - Pablo Picasso',
        '"The best way out is always through." - Robert Frost',
        '"Do what you feel in your heart to be right, for you`ll be criticized anyway." - Eleanor Roosevelt',
        '"Success is getting what you want, happiness is wanting what you get." - W. P. Kinsella',
        '"Life is either a daring adventure or nothing at all." - Helen Keller',
        '"The only impossible journey is the one you never begin." - Tony Robbins',
        '"Life itself is the most wonderful fairy tale." - Hans Christian Andersen',
        '"Do not go where the path may lead, go instead where there is no path and leave a trail." - Ralph Waldo Emerson',
        '"It is not the length of life, but the depth." - Ralph Waldo Emerson',
        '"Success is not how high you have climbed, but how you make a positive difference to the world." - Roy T. Bennett',
        '"The only thing standing between you and your goal is the story you keep telling yourself." - Jordan Belfort',
        '"Life is 10% what happens to us and 90% how we react to it." - Charles R. Swindoll',
        '"Do not be afraid to give up the good to go for the great." - John D. Rockefeller',
        '"Happiness depends upon ourselves." - Aristotle',
        '"Change the world by being yourself." - Amy Poehler',
        '"If you tell the truth, you don`t have to remember anything." - Mark Twain',
        '"Happiness is not something ready made. It comes from your own actions." - Dalai Lama',
        '"Strive not to be a success, but rather to be of value." - Albert Einstein',
        '"Injustice anywhere is a threat to justice everywhere." - Martin Luther King Jr.',
        '"Turn your wounds into wisdom." - Oprah Winfrey',
        '"Whatever you are, be a good one." - Abraham Lincoln',
       ]

       document.getElementById("text").innerHTML = (citat[Math.floor(Math.random() * 50)])
}